config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birthday    :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
  COLORS = %w(RED BLACK WHITE BROWN GREEN YELLOW BLUE ORANGE SILVER PURPLE INDIGO GREY PINK)
  validates :name, presence: true
  validates :sex, :inclusion => {in: %w(M F),
  message: "not valid gender"}
  validates :color, :inclusion => {in: %w(RED BLACK WHITE BROWN GREEN YELLOW BLUE ORANGE SILVER PURPLE INDIGO GREY PINK),
  message: "not valid color"}

  has_many :catsrequets,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest,
    dependent: :destroy
end

app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING")
#

class CatRentalRequest < ApplicationRecord
  validates :status, :inclusion => {in: %w(APPROVED DENIED PENDING),
    message: "APPROVED or DENIED"}
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, presence: true
  validates :cat_id, presence: true
  validate :does_not_overlap_approved_request

  belongs_to :cat,
    foreign_key: :cat_id,
    class_name: :Cat

  def overlapping_requests
    CatRentalRequest.where(cat_id: self.cat_id).where(start_date: self.start_date..self.end_date)
        .where(end_date: self.start_date..self.end_date)
  end

  def overlapping_approved_requests
    overlapping_requests.where(status: 'APPROVED')
  end

  def does_not_overlap_approved_request
    !overlapping_approved_requests.exists?
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])

    if @cat
      render :show
    else
      render json: @cat.errors.full_messages, status: 404
    end
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages, status: 422
    end
  end

  def update
    @cat = Cat.find(params[:id])

    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages, status: 422
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def cat_params
    params.require(:cat).permit(:color, :name, :description, :sex, :birthday)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<% if action == :create %>
  <% action_url = cats_url %>
<% else %>
  <% action_url = cat_url(cat) %>
<% end %>

<form action="<%=action_url%>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <label>What is the name of the cat
    <br>
    <input type="text" name="cat[name]" value="<%= cat.name %>">
  </label>
  <br>
  <div>
    <p> What is the gender of your cat </p>
    <input type="radio" id="M" name='cat[sex]' value='M'>
    <label for = "M"> M </label>
    <input type="radio" id="F" name='cat[sex]' value='F'>
    <label for = "F"> F </label>
  <br>
  <br>
  <label for="color">Please select a color of your cat
  <select name="cat[color]">
      <option value="">-- select a color --</option>
    <% Cat::COLORS.each do |color| %>
      <option value="<%=color%>"><%=color%></option>
    <% end %>
  </select>
</label>
  <br>
  <br>
  <label for="date"> Please select birthday of your cat </label>
  <input type="date" name="cat[birthday]" value="<%= cat.birthday %>">
  <br>
  <br>
  <label for="description">">please describe your cat</label>
  <input type="text" name="cat[description]" value="<%=cat.description%>">
  <br>
  <input type="submit" value="<%= action == :create ? "Create Cat" : "Update Cat" %>">
</form>

app/views/cats/edit.html.erb
<%= render 'form', cat: @cat, action: :edit %>

app/views/cats/index.html.erb
<h1> Checkout our Cats </h2>

<% @cats.each do |cat| %>
  <ul>NAME - <%= cat.name %>
    <li>Birthday - <%= cat.birthday %></li>
    <li>Color - <%= cat.color %></li>
    <li>Sex - <%= cat.sex %></li>
    <li>Description -<%= cat.description %></li>
  </ul>
<% end %>

app/views/cats/new.html.erb
<%= render 'form', cat: @cat, action: :create %>

app/views/cats/show.html.erb
<ul>NAME - <%= @cat.name %>
    <li>Birthday - <%= @cat.birthday %></li>
    <li>Color - <%= @cat.color %></li>
    <li>Sex - <%= @cat.sex %></li>
    <li>Description -<%= @cat.description %></li>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>